### ISSUE TITLE
Milestone 01 - Set up Kanban Board

### ISSUE THREAD

**Issue by mavericksbalitaan** [ger619/ruby-capstone#37]
In this Ruby Capstone Project,
we are a team of 3 members (@mavericks-db, @ger619 and @ramrod433)

**Link to the [GitHub project](https://github.com/ger619/ruby-capstone)**

Assigned Roles:
- Team Member 1 @mavericks-db 
- Team Member 2 @ger619 
- Team Member 3 @ramrod433

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @ger619, @mavericks-db, and @ramrod433👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] Most of the task cards are missing the description, Please make sure that all task cards have a description.
![image](https://user-images.githubusercontent.com/83803414/182122007-5499f342-15b7-4964-9b80-c6b212b950a5.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
